# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41ed1bf25008e1c9ec439720e777fa040a6f59b1e368cc7aa848e813bfd28e97360f1ce157f6fe9e337f817b046d6305328e949661c3ba02b6e946e241688792

test:
  secret_key_base: eb6f3325645ff9605535cc835601b4ae5b22a24844685441e99c3941112bcf911461a1f94fb81224ec17a704110968feb743e60885137afba7d1aac626c58900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
